{% set name = "gluonts" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gluonts-{{ version }}.tar.gz
  sha256: af1a12b9f22f8db071f31da518a9c61f1539b0036d857826c88091032bb9a845

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16,<2.dev0
    - pandas >=1.0,<2.2.0
    - pydantic >=1.7,<3.dev0
    - tqdm >4.23,<5.dev0
    - toolz >=0.10,<1.dev0
    - typing-extensions >=4.0,<5.dev0
    - pytorch
    - pytorch-lightning
    - protobuf

test:
  imports:
    - gluonts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/gluonts/
  summary: GluonTS is a Python toolkit for probabilistic time series modeling, built around MXNet.
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - claytonparnell
    - giswqs
